# models.py - Pydantic Schemas for Structured Output and Agents

from pydantic import BaseModel, Field
from typing import List, Optional

# =======================================================
# 1. Reader Agent Models
# =======================================================

class Segment(BaseModel):
    """A segment of structured study material."""
    type: str = Field(description="The type of content, e.g., 'Definition', 'Key Takeaway', 'Example', 'Subtopic'.")
    content: str = Field(description="The extracted text content for this segment.")

class TopicStructure(BaseModel):
    """The structured output for a single topic."""
    topic_name: str = Field(description="The main topic derived from the text.")
    summary: str = Field(description="A brief, one-sentence summary of the topic.")
    key_segments: List[Segment] = Field(description="A list of structured segments (definitions, takeaways) extracted from the topic.")

class StructuredNotes(BaseModel):
    """The final structured notes containing one or more topics."""
    file_name: str = Field(description="The name of the original uploaded file.")
    topics: List[TopicStructure] = Field(description="A list of all major topics processed and structured.")

# =======================================================
# 2. Flashcard Agent Models
# =======================================================

class Flashcard(BaseModel):
    """A single question/answer flashcard."""
    question: str = Field(description="The question derived from the study material segment.")
    answer: str = Field(description="The concise answer to the question.")
    topic_tag: str = Field(description="The main topic this flashcard belongs to.")

class FlashcardDeck(BaseModel):
    """A collection of generated flashcards."""
    cards: List[Flashcard]

# =======================================================
# 3. Quiz Agent Models
# =======================================================

class QuizOption(BaseModel):
    """A single option for a multiple-choice question."""
    option_text: str = Field(description="The text of the answer choice.")
    option_id: int = Field(description="A unique integer ID for this option (0, 1, 2, 3...).")

class QuizQuestion(BaseModel):
    """A single multiple-choice question."""
    question_text: str = Field(description="The question based on the study material.")
    options: List[QuizOption] = Field(description="A list of 4 answer options (0-3).")
    correct_option_id: int = Field(description="The option_id of the correct answer.")
    topic_tag: str = Field(description="The topic tag related to this question.")
    
class GeneratedQuiz(BaseModel):
    """The full quiz generated by the agent."""
    quiz_id: str = Field(description="A unique UUID for this quiz instance.")
    questions: List[QuizQuestion]
    
# Used for quiz submission tracking
class QuizAnswer(BaseModel):
    """Model for receiving a single user answer before scoring."""
    question_index: int
    selected_option_id: int
    correct_option_id: int
    topic: str
    
class QuizSubmission(BaseModel):
    """Model for receiving the entire user quiz submission."""
    quiz_id: str
    answers: List[QuizAnswer]